#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02

apt -y update
apt-get -y haproxy

config="
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 245918-web-01 18.204.15.208:80 check
    server 245918-web-02 54.209.7.164:80 check
"

echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
